[package]
authors = ["Joshua Smith <jsmith62831@gmail.com>"]
name = "basis-blade"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num-traits = "^0.2"
